"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])

# ✨ A deployed environment sits behind a proxy that ends TLS (docs/server-approach.md). Only then is the
# proxy's word taken for whether a request came over HTTPS, which is what marks the observer's cookie
# Secure. Unset, as in development, no forwarded header is trusted and nothing insists on HTTPS.
if env.bool("DJANGO_HTTPS", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # ✨ The health check is asked for over plain HTTP, straight at the pod, and must answer there.
    SECURE_REDIRECT_EXEMPT = [r"^healthz$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = env.int("DJANGO_HSTS_SECONDS", default=0)

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

# ✨ The commit the running code was built from, which /healthz reports. The image sets it.
ANVILLE_COMMIT = env("ANVILLE_COMMIT", default="unknown")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "access",  # ✨ before allauth, so its templates override allauth's layout
    "allauth",
    "allauth.account",
    "engine",
    "organisations",
    "django_vite",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_ADAPTER = "access.adapter.AccountAdapter"
LOGIN_REDIRECT_URL = "hub"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"  # ✨ the header's "Sign out" leads to the homepage (ticket 41a)
ACCOUNT_SIGNUP_FORM_CLASS = "access.forms.EnrolmentCodeSignupForm"
ACCOUNT_FORMS = {"login": "access.forms.SignInForm"}
# ✨ On unless the environment turns it off, so a deployment that forgets the setting admits nobody without the code.
ANVILLE_ENROLMENT_REQUIRED = env.bool("ANVILLE_ENROLMENT_REQUIRED", default=True)
ANVILLE_ENROLMENT_CODE = env("ANVILLE_ENROLMENT_CODE", default="")
# ✨ Set on a demo deployment, whose sign-up is open: the homepage and the account pages show it (ticket 26).
ANVILLE_DEMO_NOTICE = env("ANVILLE_DEMO_NOTICE", default="")
# ✨ The pathway sidebar the header opens on every participant page (ticket 41a). Off leaves the header, its link to
# the hub and "Sign out".
ANVILLE_SIDEBAR = env.bool("ANVILLE_SIDEBAR", default=True)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "access.context_processors.demo_notice",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        **env.db("DATABASE_URL"),
        # ✨ Seconds to keep a connection for reuse. 0, the default, closes it after each request.
        "CONN_MAX_AGE": env.int("DATABASE_CONN_MAX_AGE", default=0),
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "frontend" / "dist"]

# ✨ Where collectstatic gathers everything for WhiteNoise to serve, so a deployed environment needs no
# second web server. Development never needs it: with DJANGO_DEBUG on, files are found where they are.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# ✨ Vite puts a hash of the content in each built file's name, so those may be cached for good.
WHITENOISE_IMMUTABLE_FILE_TEST = r"^/static/assets/.+-[\w-]{8}\.\w+$"

# ✨ Files a pathway's download blocks offer, such as the workbook (ticket 40). Served by a view that checks the
# participant has reached the block, never as static files, which anyone could fetch.
PATHWAY_FILES_DIR = BASE_DIR / "pathways" / "files"

DJANGO_VITE = {
    "default": {
        "manifest_path": BASE_DIR / "frontend" / "dist" / "manifest.json",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/

# ✨ One URL names the provider, such as smtp+tls://key:secret@host:587. Unset, email is fake: each
# message is printed where the server's output goes, and nothing is delivered.
# An empty value counts as unset, since a deployment may hand over a secret it has not been given.
vars().update(env.email_url_config(env("EMAIL_URL", default="") or "consolemail://"))

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="webmaster@localhost")

# ✨ Set on a test system that can reach real mailboxes: every message then says, in its subject and at the top
# of its body, that it is not from the real service. It wraps whichever backend the lines above chose.
ANVILLE_EMAIL_DISCLAIMER = env("ANVILLE_EMAIL_DISCLAIMER", default="")
if ANVILLE_EMAIL_DISCLAIMER:
    ANVILLE_DISCLAIMED_EMAIL_BACKEND = EMAIL_BACKEND  # noqa: F821  (set by vars().update above)
    EMAIL_BACKEND = "config.email.DisclaimerBackend"


# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/

# ✨ With DJANGO_DEBUG off Django prints nothing, so a deployed environment would fail in silence. This
# sends errors to the server's output, with the secret taken out of any observer's or coach's link named.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
        "redact_links": {"()": "config.logs.RedactLinks"},
    },
    "handlers": {
        "errors": {
            "class": "logging.StreamHandler",
            "level": "ERROR",
            "filters": ["require_debug_false", "redact_links"],
        },
    },
    "root": {"handlers": ["errors"]},
    # ✨ Anyone scanning the address sends a wrong Host header, and Django answers 400. Not worth a traceback each.
    "loggers": {"django.security.DisallowedHost": {"handlers": [], "propagate": False}},
}
