# Generated by Django 5.2.17 on 2026-10-09 07:14

import django.db.models.deletion
import organisations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('cohort', 'Cohort'), ('team', 'Team')], max_length=16)),
                ('join_token', models.CharField(default=organisations.models.new_join_token, editable=False, max_length=64, unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organisations.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'group'), name='one_membership_per_participant_per_group')],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('manage', 'Manage'), ('see_progress', 'See progress')], max_length=16)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='organisations.group')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_permissions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='organisations.organisation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('organisation__isnull', False)), models.Q(('group__isnull', False), ('organisation__isnull', True)), _connector='OR'), name='a_permission_names_an_organisation_or_a_group')],
            },
        ),
    ]
