# Copyright (C) New Community Church SE London 2026.
# For licensing information see ../../LICENSE.md

# Generated by Django 5.2.17 on 2026-09-25 08:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_version', models.PositiveIntegerField()),
                ('given_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
