# Generated by Django 5.2.17 on 2026-09-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    # ✨ Enforced by PostgreSQL, not by convention: any UPDATE or DELETE of a stored pathway version is
    # refused, however it arrives (the ORM, a raw query, psql). TRUNCATE is deliberately not blocked,
    # because Django's flush (and so every transactional test) clears tables with it.
    operations = [
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION engine_refuse_pathway_version_change() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'A pathway version cannot be modified or deleted once stored.';
                END
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER pathway_version_is_immutable
                    BEFORE UPDATE OR DELETE ON engine_pathwayversion
                    FOR EACH ROW EXECUTE FUNCTION engine_refuse_pathway_version_change();
            """,
            reverse_sql="""
                DROP TRIGGER pathway_version_is_immutable ON engine_pathwayversion;
                DROP FUNCTION engine_refuse_pathway_version_change();
            """,
        ),
    ]
