# Copyright (C) New Community Church SE London 2026.
# For licensing information see ../../LICENSE.md

# Generated by Django 5.2.17 on 2026-09-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='fixed_answers',
            field=models.JSONField(default=dict),
        ),
    ]
