# Generated by Django 5.2.17 on 2026-09-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_response_fixed_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('coach', 'Coach'), ('contact', 'Contact')], max_length=16)),
                ('position', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='engine.response')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('response', 'block_id', 'position'), name='one_contact_per_row')],
            },
        ),
    ]
