# Generated by Django 5.2.17 on 2026-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='pages_moved_past',
            field=models.JSONField(default=dict),
        ),
    ]
