# Generated by Django 5.2.17 on 2026-09-30 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_response_pages_moved_past'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='engine.contact')),
            ],
        ),
    ]
