# Copyright (C) New Community Church SE London 2026.
# For licensing information see ../../LICENSE.md

# Generated by Django 5.2.17 on 2026-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='secret_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
