# Copyright (C) New Community Church SE London 2026.
# For licensing information see ../../LICENSE.md

# Generated by Django 5.2.17 on 2026-09-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_invitation_claimed_at_invitation_secret_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObserverResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.JSONField(blank=True, null=True)),
                ('written_answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_test_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observer_responses', to='engine.response')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('submitted_at__isnull', True), ('assessment__isnull', False), _connector='OR'), name='a_submitted_observer_response_holds_an_assessment')],
            },
        ),
    ]
