# Generated by Django 5.2.17 on 2026-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_observerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='observerresponse',
            name='sent_by',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
