# Copyright (C) New Community Church SE London 2026.
# For licensing information see ../../LICENSE.md

# Generated by Django 5.2.17 on 2026-10-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_observerresponse_sent_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='comparisons_visited',
            field=models.JSONField(default=dict),
        ),
    ]
