# Generated by Django 5.2.17 on 2026-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_response_comparisons_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='coach_answer',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=16, null=True),
        ),
    ]
